spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true

logging:
  level:
    org.hibernate.SQL: debug